# Site settings
title: "samira shalal"
description: "personal website"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "samira shalal"
resume_title:                   "pursuing B.S. in compsci and cogsci @ umich"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "samirashalal16@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "8108453330"
resume_contact_address:         "detroit, mi"

resume_header_contact_info:     "detroit, mi • (810) 845-3330 • samirashalal16@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>hello! i'm a junior CS student interested in AI/ML, AI ethics, SWE, and game dev. see my <a href='https://drive.google.com/file/d/1hL7brkvo9EnPGHZmJMl4Pwm8EE67l5mB/view?usp=sharing'>resume</a> to learn more about my experience, or my socials to learn more about me. check out what projects i'm currently working on below!</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      false
resume_section_education:       false
resume_section_projects:        true
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/n0vendy"
  resume_twitter_url:           "https://x.com/n0vendy"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/samira-shalal-130801326/"
  resume_instagram_url:         "https://instagram.com/n0vendy"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
